apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: lfq0eapo9-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-80b021abb3.clc8.p3.openshiftapps.com/rhtap/rhtap-qe:2b99adac7246cec6f7d3b08334985264d13856da@sha256:dc8794d23f089953b1ba3426b35e4bbaf32390b88892f4b2d2a784efcca5df7b
        name: container-image  
